# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: serverless

frameworkVersion: '2'

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - codepipeline:StartPipelineExecution
      Resource:
        Fn::Join:
          - ":"
          - - "arn:aws:codepipeline"
            - "Ref" : 'AWS::Region'
            - "Ref" : 'AWS::AccountId'
            - 'mfe-*'

# The `functions` block defines what code to deploy
functions:
  lexMicroFrontendChatbot:
    handler: handler.lexHandler